### ISSUE TITLE
RTE : function called on server that shouldn't be

### ISSUE THREAD

**Issue by ericcotelnu** [refinedmods/refinedpipes#100]
### Describe the bug

They don't do anything, no energy, fluid, nor item transport. I suspect it's because of : 

(see log output below)

this is straight from the log, while I was playing. It didn't crash, just nothing happened. Made some of those attachment items thinking it was a user (me) issue, but alas no. I have a whole bunch of RTEs in my log, all repeating the same error. They're listed as fatal errors.

### How can we reproduce this bug or crash?

Use mod's items normally

### What Forge version is this happening on?

36.2.22

### What Refined Pipes version is this happening on?

0.5.1

### Relevant log output

```shell
Error executing task on Server
java.lang.RuntimeException: Shouldn't be called on the server
	at com.refinedmods.refinedpipes.network.pipe.attachment.ServerAttachmentManager.getPickBlock(ServerAttachmentManager.java:48)
	at com.refinedmods.refinedpipes.block.PipeBlock.getPickBlock(PipeBlock.java:207)
	at net.minecraftforge.common.extensions.IForgeBlockState.getPickBlock(IForgeBlockState.java:326)
	at net.minecraft.server.management.PlayerInteractionManager.md627a54$lambda$diet$preBlockActivated$0$1(PlayerInteractionManager.java:1530)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165)
	at net.minecraft.server.management.PlayerInteractionManager.handler$bnp000$diet$preBlockActivated(PlayerInteractionManager.java:1528)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338)
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Darkere** [comment]
The error can be ignored. It appears there is a bug with pickblock (middle mouse click on block). That doesn't have any effect on the pipes though...

**Comment by raoulvdberge** [comment]
Pick block should be client side only. Not sure why it's being called on the server.

**Comment by ozokuz** [comment]
I'm getting this same error on mc 1.16.5 mod version 0.5.2.
Trying to place an extractor attachment on a pipe will cause this error to appear in the log and the extractor will not be placed on the pipe.
