### ISSUE TITLE
Crash Loop when attempting to pull from Create's Portable Storage Interface

### ISSUE THREAD

**Issue by andr9528** [refinedmods/refinedpipes#106]
### Describe the bug

Placing an Item pipe interacting with a Portable Storage Interface from Create, and adding an Attachment to start pulling from the Interface crashes the game on server tick. Any attempts to log back in simply crashes the game again with the same exception.

Full crash log can be found on this gist: [Log](https://gist.github.com/andr9528/c46ffb4c3dba11ec2589d3aaa642a94c)

I had no contraption interacting with the Portable Storage Interface at the moment of the crash.

### How can we reproduce this bug or crash?

1. Place down a Portable Storage Interface from Create.
2. Place a Item pipe touching the Portable Storage Interface.
3. Add an Attachment to the side touching the Portable Storage Interface.
4. Crash. Repeatedly.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.16

### What Refined Pipes version is this happening on?

0.6.0

### Relevant log output

```shell
java.lang.RuntimeException: Slot 0 not in valid range - [0,0)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[forge-1.18.1-39.0.16-universal.jar%23250!:?] {re:mixin,re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[forge-1.18.1-39.0.16-universal.jar%23250!:?] {re:mixin,re:classloading}
	at com.simibubi.create.foundation.item.ItemHandlerWrapper.getStackInSlot(ItemHandlerWrapper.java:21) ~[create-mc1.18.1_v0.4c.jar%23106!:mc1.18.1_v0.4c] {re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.attachment.extractor.ExtractorAttachment.findDestinationAndSourceSlot(ExtractorAttachment.java:169) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.attachment.extractor.ExtractorAttachment.update(ExtractorAttachment.java:132) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.attachment.extractor.ExtractorAttachment.lambda$update$0(ExtractorAttachment.java:120) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.16-universal.jar%23250!:?] {re:mixin,re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.attachment.extractor.ExtractorAttachment.update(ExtractorAttachment.java:120) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.Pipe.update(Pipe.java:30) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.pipe.item.ItemPipe.update(ItemPipe.java:34) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at com.refinedmods.refinedpipes.network.Network.update(Network.java:57) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onLevelTick$13(CommonSetup.java:160) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at com.refinedmods.refinedpipes.setup.CommonSetup.onLevelTick(CommonSetup.java:160) ~[refinedpipes-0.6.0.jar%23198!:0.6.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.16-universal.jar%23250!:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:874) ~[client-1.18.1-20211210.034407-srg.jar%23246!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23246!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23246!:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23246!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23246!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

**Comment by andr9528** [comment]
Saved my world by deleting the Portable Storage Interface using Amulet (WorldEdit Program). 
Time to find some other mod to pull out of the Portable Storage Interface, until Refined Pipes gets fixed.
