### ISSUE TITLE
Crash when removing a fluid pipe whit shaders

### ISSUE THREAD

**Issue by Jonichimang** [refinedmods/refinedpipes#12]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 13/05/20 02:58 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=north, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:mixin,re:classloading}
	at com.raoulvdberge.refinedpipes.render.FluidPipeTileEntityRenderer.render(FluidPipeTileEntityRenderer.java:54) ~[?:0.4.1] {re:classloading}
	at com.raoulvdberge.refinedpipes.render.FluidPipeTileEntityRenderer.func_225616_a_(FluidPipeTileEntityRenderer.java:20) ~[?:0.4.1] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:103) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:167) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:441) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.87.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.87.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93)
	at com.raoulvdberge.refinedpipes.render.FluidPipeTileEntityRenderer.render(FluidPipeTileEntityRenderer.java:54)
	at com.raoulvdberge.refinedpipes.render.FluidPipeTileEntityRenderer.func_225616_a_(FluidPipeTileEntityRenderer.java:20)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:137)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:103)

-- Block Entity Details --
Details:
	Name: refinedpipes:basic_fluid_pipe // com.raoulvdberge.refinedpipes.tile.FluidPipeTileEntity
	Block: Block{refinedpipes:basic_fluid_pipe}[down=false,east=true,inv_down=false,inv_east=false,inv_north=false,inv_south=false,inv_up=false,inv_west=false,north=false,south=false,up=false,west=false]
	Block location: World: (171,4,-215), Chunk: (at 11,0,9 in 10,-14; contains blocks 160,0,-224 to 175,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{minecraft:air}
	Block location: World: (171,4,-215), Chunk: (at 11,0,9 in 10,-14; contains blocks 160,0,-224 to 175,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:167)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:97)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:441)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926)

**Comment by SonicSpeedster16** [comment]
I encountered this exact crash last night while breaking a fluid pipe with lava in it and BSL shaders in use.

**Comment by benzenebanana** [comment]
I also encountered this crash in Stacia Expert multiple times without running optifine or shaders
