### ISSUE TITLE
[1.18.1] Invalid capability class casting exception causing crash

### ISSUE THREAD

**Issue by robotgryphon** [refinedmods/refinedpipes#96]
### Describe the bug

It appears that item pipes are erroneously trying to cast capabilities - I have a debug capability that provides infinite items, and it seems RP tried to cast the cap instance to a fluid handler:

```
java.lang.ClassCastException: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:95) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.item.ItemNetwork.scanGraph(ItemNetwork.java:35) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.update(Network.java:54) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onLevelTick$13(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at com.refinedmods.refinedpipes.setup.CommonSetup.onLevelTick(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
```

### How can we reproduce this bug or crash?

1. Have something that provides item handling capabilities
2. Place a pipe down
3. Observe crash?

There may be more involved here (LO invalidation, not casting on my end) but figured I'd put it here for tracking.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.0

### What Refined Pipes version is this happening on?

0.6.0 (refinedpipes-370696-3570151_mapped_official_1.18.1)

### Relevant log output

```shell
[06:41:47] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:95) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.item.ItemNetwork.scanGraph(ItemNetwork.java:35) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.NetworkManager.formNetworkAt(NetworkManager.java:76) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.NetworkManager.addPipe(NetworkManager.java:132) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.blockentity.PipeBlockEntity.clearRemoved(PipeBlockEntity.java:53) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockEntity(LevelChunk.java:345) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.level.chunk.LevelChunk.addAndRegisterBlockEntity(LevelChunk.java:314) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:253) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:202) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:179) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.item.BlockItem.placeBlock(BlockItem.java:161) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.item.BlockItem.place(BlockItem.java:66) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.world.item.BlockItem.useOn(BlockItem.java:46) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:574) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:212) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:350) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:975) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:28) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:21) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:17) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:139) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:22) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:765) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:161) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:112) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:748) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:742) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:122) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:728) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:672) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[06:41:47] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4249/0x000000080163def0@74fbe93
		2: ASM: class com.simibubi.create.events.CommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		3: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkListener@6abc69c1 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
java.lang.ClassCastException: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	at TRANSFORMER/forge@39.0.0/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:95)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.item.ItemNetwork.scanGraph(ItemNetwork.java:35)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.network.Network.update(Network.java:54)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onLevelTick$13(CommonSetup.java:160)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at TRANSFORMER/refinedpipes@0.6.0/com.refinedmods.refinedpipes.setup.CommonSetup.onLevelTick(CommonSetup.java:160)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.0/net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:874)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:808)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:86)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:668)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[06:41:47] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:95) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.item.ItemNetwork.scanGraph(ItemNetwork.java:35) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.network.Network.update(Network.java:54) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onLevelTick$13(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at com.refinedmods.refinedpipes.setup.CommonSetup.onLevelTick(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%239!:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%239!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%239!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%239!:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:874) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:808) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:86) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:668) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/22/21, 6:41 AM
Description: Exception in server tick loop

java.lang.ClassCastException: class dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource cannot be cast to class net.minecraftforge.fluids.capability.IFluidHandler (dev.compactmods.machines.tunnel.ItemImportTunnel$InfiniteItemSource is in module compactmachines@0.0NONE of loader 'TRANSFORMER' @7640a5b1; net.minecraftforge.fluids.capability.IFluidHandler is in module forge@39.0.0 of loader 'TRANSFORMER' @7640a5b1)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:95) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.item.ItemNetwork.scanGraph(ItemNetwork.java:35) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.update(Network.java:54) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onLevelTick$13(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at com.refinedmods.refinedpipes.setup.CommonSetup.onLevelTick(CommonSetup.java:160) ~[refinedpipes-370696-3570151_mapped_official_1.18.1.jar%2391!:0.6.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%239!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%239!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2376%2382!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:874) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:808) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:86) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:668) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258) ~[forge-1.18.1-39.0.0_mapped_official_1.18.1-recomp.jar%2377!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

**Comment by raoulvdberge** [comment]
This is not a Refined Pipes issue. The capability is exposed in an invalid way.
