### ISSUE TITLE
[1.18.1] Pipe model causes cast exception/broken events

### ISSUE THREAD

**Issue by Ribbons0121R121** [refinedmods/refinedpipes#97]
### Describe the bug

model seems to cause a buncha errors with pipe blocks in general, crashes too much for me to test all pipe types. it happened with the tier 3 item pipe if it helps.

### How can we reproduce this bug or crash?

1.Place a pipe(first error, cast exception).
2.Break the pipe(second error, event exception.)
thats it.

### What Forge version is this happening on?

39.0.8

### What Refined Pipes version is this happening on?

The only one for 1.18 currently

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.m_7541_()" because "this.core" is null
	at com.refinedmods.refinedpipes.render.PipeBakedModel.m_7541_(PipeBakedModel.java:189) ~[refinedpipes-0.6.0.jar%23110!:0.6.0] {re:classloading}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:48) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:67) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:629) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:548) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_194412_(ChunkRenderDispatcher.java:121) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.m_6160_()" because "this.core" is null
	at com.refinedmods.refinedpipes.render.PipeBakedModel.m_6160_(PipeBakedModel.java:210) ~[refinedpipes-0.6.0.jar%23110!:0.6.0] {re:classloading}
	at net.minecraftforge.client.extensions.IForgeBakedModel.getParticleIcon(IForgeBakedModel.java:81) ~[forge-1.18.1-39.0.8-universal.jar%23136!:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.BlockModelShaper.m_110882_(BlockModelShaper.java:29) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:placebo.mixins.json:BlockModelShaperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.TerrainParticle.<init>(TerrainParticle.java:26) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.m_172270_(ParticleEngine.java:460) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.ParticleManagerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.phys.shapes.VoxelShape.m_83234_(VoxelShape.java:93) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:VoxelShapeAccess,pl:mixin:A}
	at net.minecraft.world.phys.shapes.BitSetDiscreteVoxelShape.m_165963_(BitSetDiscreteVoxelShape.java:202) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BitSetDVSAccess,pl:mixin:A}
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.m_82832_(DiscreteVoxelShape.java:197) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:DiscreteVSAccess,pl:mixin:A}
	at net.minecraft.world.phys.shapes.VoxelShape.m_83286_(VoxelShape.java:93) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:VoxelShapeAccess,pl:mixin:A}
	at net.minecraft.client.particle.ParticleEngine.m_107355_(ParticleEngine.java:443) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.ParticleManagerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_142052_(ClientLevel.java:772) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109532_(LevelRenderer.java:2757) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_5898_(ClientLevel.java:540) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.block.Block.m_142387_(Block.java:412) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:BlockMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_5707_(Block.java:416) ~[client-1.18.1-20211210.034407-srg.jar%23132!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:BlockMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeBlock.onDestroyedByPlayer(IForgeBlock.java:179) ~[forge-1.18.1-39.0.8-universal.jar%23136!:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.onDestroyedByPlayer(IForgeBlockState.java:136) ~[forge-1.18.1-39.0.8-universal.jar%23136!:?] {re:mixin,re:classloading}
```

**Comment by raoulvdberge** [comment]
Fixed by #104
